### ISSUE TITLE
Program is immediately exited with error when config file is empty

### ISSUE THREAD

**Issue by jaroslav-kubicek** [falsecz/easy-pg#13]
When I load config file that is empty, incomprehensible error is thrown and program exits with error:

```
TypeError: Cannot read property 'stack' of undefined
  at Object.exports.load (/Users/kubajz/projects/cheddar/node_modules/cson-config/index.coffee:51:5)
```

The problem lies in this condition: `if c.stack?`, because variable c is undefined in case of empty file.

**Comment by falsecz** [comment]
how is cson-config related to cson-config ?

**Comment by jaroslav-kubicek** [comment]
Damn, Friday :-/ I clicked on bad repository, nevermind.
