### ISSUE TITLE
["native"] Fails Upserts  node v4.1.2

### ISSUE THREAD

**Issue by lgwaustralia** [falsecz/easy-pg#14]
Currently getting an issue with node v4.1.2 and npm 2.14.4 Running mac osx 10.9.5
This seemed to happen after an update to the latest version of node.js
error in upsert=Error: Module did not self-register.
error in upsert=TypeError: Cannot read property 'hasOwnProperty' of undefined.
PS Thanks for the great module!  Really helps a lot having your upsert function available.

**Comment by wision** [comment]
Native support was dropped as of v2.0.2
